install_elixir: &install_elixir
  run:
    name: Install Elixir
    command: |
      wget https://repo.hex.pm/builds/elixir/v$ELIXIR_VERSION.zip
      unzip -d /usr/local/elixir v$ELIXIR_VERSION.zip
      echo 'export PATH=/usr/local/elixir/bin:$PATH' >> $BASH_ENV

install_archives: &install_archives
  run:
    name: Install Archives
    command: |
      mix do local.hex --force, local.rebar --force, archive.install hex nerves_bootstrap ${NERVES_BOOSTRAP} --force

version: 2
jobs:
  build:
    docker:
      - image: erlang:22.2.1
        environment:
          ELIXIR_VERSION: 1.9.4-otp-22
          NERVES_BOOTSTRAP: ~> 1.5
          LC_ALL: C.UTF-8
    working_directory: ~/repo
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - <<: *install_elixir
      - <<: *install_archives
      - run: mix format --check-formatted
      - run: mix deps.get --only test
      - run: mix test --exclude with_plc
      - run: mix docs
